### ISSUE TITLE
Experiment with socket connections to remote machines

### ISSUE THREAD

**Issue by jpsember** [jpsember/dev#40]

**Comment by jpsember** [comment]
Maybe this is helpful:
https://www.baeldung.com/java-ssh-connection

**Comment by jpsember** [comment]
I'm getting this problem attempting to connect:
```
(ExperimentOper:) ...looking for arguments in: exp-args.json
identity added 
session created
Exception in thread "main" java.lang.RuntimeException: com.jcraft.jsch.JSchException: USERAUTH fail
	at js.base.Tools.asRuntimeException(Tools.java:503)
	at dev.ExperimentOper.perform(ExperimentOper.java:62)
	at js.app.App.auxRunOper(App.java:130)
	at js.app.App.runApplication(App.java:121)
	at js.app.App.startApplication(App.java:90)
	at dev.Main.main(Main.java:38)
Caused by: com.jcraft.jsch.JSchException: USERAUTH fail
	at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:119)
	at com.jcraft.jsch.Session.connect(Session.java:470)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at dev.ExperimentOper.listFolderStructure(ExperimentOper.java:95)
	at dev.ExperimentOper.perform(ExperimentOper.java:60)
	... 4 more
```

**Comment by jpsember** [comment]
Went down a rabbit hole with:

https://gist.github.com/niclasnilsson/038f20bee1bd19e970d59ba35732e262

Tried a bunch of stuff as it suggests, with no luck.

Did I have a passphrase on my rsa key?

**Comment by jpsember** [comment]
Ok, I got it working...

jsch is incompatible with some of the headers in the private keys:

https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

- [ ]  will all devices running the jsch library need to make this change?
- [ ]  can I go back to an empty keyphrase?
- [ ]  do I still need to modify/hide the .ssh/config file?

**Comment by jpsember** [comment]
Javadoc:  https://epaul.github.io/jsch-documentation/javadoc/
