### ISSUE TITLE
Unit test failing on remote machine only

### ISSUE THREAD

**Issue by jpsember** [jpsember/dev#8]
```
forgotten(dev.ArchiveOperTest)  Time elapsed: 0.028 sec  <<< FAILURE!
java.lang.AssertionError: 
Unexpected hash value for directory contents:
--------------------------------------------------------------------------
{ "local" : { ".archive_registry.json" : { "entries" : { "gamma.txt" : {    "path" : "gamma.txt",
                                                                            "push" : false,
                                                                         "version" : 1
                                                                       } },
                                           "version" : "2.0"
                                         },
                               "alpha" : { "beta.txt" : "beta.txt\n" },
               "archive_registry.json" : { "entries" : { "gamma.txt" : {    "path" : "gamma.txt",
                                                                         "version" : 1
                                                                       } },
                                           "version" : "2.0"
                                         },
                           "gamma.txt" : ""
            } }
--------------------------------------------------------------------------
	at org.junit.Assert.fail(Assert.java:88)
	at js.testutil.FileManager.assertGeneratedDirectoryHash(FileManager.java:93)
	at js.testutil.MyTestCase.assertGenerated(MyTestCase.java:287)
```

**Comment by jpsember** [comment]
I should generate a warning if the test encounters an empty directory, in the summary map.
